### ISSUE TITLE
Реализовать вариант 2

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#14]
Необходимо реализовать расчёт параметров резервуара в соответствие с [Вариантом №2](https://docs.google.com/document/d/1mgUwp20D0uvH53vgxJbwfOQ8Tq3IU0_MuJ8oBSSNYOI).

Для этого:
- создать новую [Ветку](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches) 
- оформить план работ: создать набор задач, которые необходимо решить для реализации варианта №2
- реализовать в созданной ветке вариант №2 в соответствии с планом работ.

**Comment by Ted-Denisenko** [comment]
@dr-silence > Параметры резервуара и его содержимого указываются пользователем в командной строке
Я правильно понимаю, что программа должна вызываться из командной строки и ввод данных теперь должен быть организован через параметры командной строки, а не консоль студии, как было сделано в первом варианте?

**Comment by dr-silence** [comment]
Верно, программа должна запускаться (вызываться) из командной строки. Как это и делается уже сейчас.
Верно, входные данные должны казался пользователем в строке запуска программы, а не вводится им а окне программы.

**Comment by Ted-Denisenko** [comment]
Сделано в [этом](https://github.com/Ted-Denisenko/Storage_tank/commit/7ee9384e123d5e590faf8025c63053567a8aabb8) коммите
