### ISSUE TITLE
Использовать Boost.Program_options

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#18]
При реализации #14 для разбора аргументов строки запуска приложения необходимо использовать [Boost.Program_options](https://www.boost.org/doc/libs/1_79_0/doc/html/program_options.html).

**Comment by Ted-Denisenko** [comment]
Начиная с [этого] коммита(https://github.com/Ted-Denisenko/Storage_tank/pull/19),в проекте используется boost.program_options
