### ISSUE TITLE
Создать проект для вариантов №№ 2, 2.1

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#25]
С целью организации работ по реализации вариантов 2, 2.1 необходимо создать [проект GitHub](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects).

**Comment by Ted-Denisenko** [comment]
[Вариант 2](https://github.com/users/Ted-Denisenko/projects/1/views/1)
[Вариант 2.1](https://github.com/users/Ted-Denisenko/projects/2/views/1)

**Comment by dr-silence** [comment]
> [Вариант 2](https://github.com/users/Ted-Denisenko/projects/1/views/1) [Вариант 2.1](https://github.com/users/Ted-Denisenko/projects/2/views/1)

404

**Comment by Ted-Denisenko** [comment]
@dr-silence , проверь еще раз, я отправил приглашение от обоих проектов
