### ISSUE TITLE
Реализовать вариант №2.2

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#37]
Необходимо реализовать расчёт параметров содержимого резервуара в соответствии с [вариантом 2.2](https://docs.google.com/document/d/1mgUwp20D0uvH53vgxJbwfOQ8Tq3IU0_MuJ8oBSSNYOI).

**Comment by Ted-Denisenko** [comment]
"...не должны зависеть от региональных настроек."
@dr-silence , я правильно понимаю, что имеется в виду работа с локалями, используя [std::locale](https://en.cppreference.com/w/cpp/locale/locale)?

**Comment by dr-silence** [comment]
Правильно.

**Comment by Ted-Denisenko** [comment]
@dr-silence , я правильно понимаю, что нужно установить одну локаль для всей программы? Например, до обработки аргументов командной строки установить локаль Н, и сделать также перед любым выводом в консоль?

**Comment by dr-silence** [comment]
Позже.

**Comment by dr-silence** [comment]
Позже.
