### ISSUE TITLE
Научиться выводить значения с учётом региона пользователя

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#38]
Если приложение запускается пользователем ОС, использующим регион "Россия", например, то при выводе вещественных чисел используется разделитель "запятая":
- 3,14
- 7,62

Если же приложение запускается пользователем, использующим регион "США", например, то при выводе вещественных чисел используется разделитель "запятая":
- 3.14
- 7.62

**Comment by dr-silence** [comment]
Необходимо научиться выводить значения как с использованием [потокового ввода/вывода](https://en.cppreference.com/w/cpp/io) (потоков), так и с использованием [вводы/вывода в стиле C](https://en.cppreference.com/w/cpp/io/c) (C-style ввод/вывод).

**Comment by dr-silence** [comment]
Возможно, что для решения этой задачи будет лучше создать отдельный репозиторий.

**Comment by Ted-Denisenko** [comment]
> Возможно, что для решения этой задачи будет лучше создать отдельный репозиторий.

Создал отдельный [репозиторий](https://github.com/Ted-Denisenko/Locales_training) для тренировки работы с локалями

**Comment by dr-silence** [comment]
> > Возможно, что для решения этой задачи будет лучше создать отдельный репозиторий.
> 
> Создал отдельный [репозиторий](https://github.com/Ted-Denisenko/Locales_training) для тренировки работы с локалями

@Ted-Denisenko необходимо либо перенести эту задачу в новый репозиторий, либо скопировать её туда же и затем закрыть.

**Comment by dr-silence** [comment]
Позже.
