### ISSUE TITLE
Расчёт объёма содержимого горизонтального резервуара

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#39]
Реализовать расчёт объёма содержимого горизонтального резервуара ([Вариант №3](https://docs.google.com/document/d/1mgUwp20D0uvH53vgxJbwfOQ8Tq3IU0_MuJ8oBSSNYOI/edit?usp=sharing):
- тип резервуара указывается пользователем в командной строке приложения;
- реализовать тесты, используя как эталон результаты вычислений [онлайн-калькулятора](https://planetcalc.ru/762/).

**Comment by Ted-Denisenko** [comment]
@dr-silence , нужно ли в данной задаче рассматривать случай, когда пользователь сделал ошибочный ввод?
(пример: нужно ввести аргумент "h" для расчета горизонтального резервуара и "v" для вертикального, но пользователь ввел "abc")

**Comment by dr-silence** [comment]
@Ted-Denisenko учтён ли случай, когда уровень содержимого больше половины высоты резервуара?

**Comment by Ted-Denisenko** [comment]
> учтён ли случай, когда уровень содержимого больше половины высоты резервуара?

Да, в таком случае вычисления также верны
