### ISSUE TITLE
Ошибки компиляции при попытке высчитать объем горизонтального контейнера

### ISSUE THREAD

**Issue by Ted-Denisenko** [Ted-Denisenko/Storage_tank#40]
Все изменения и код в [этом](https://github.com/Ted-Denisenko/Storage_tank/commit/a903ae86168e60cd950c138421853f22211b30ea) коммите

Необходимо посчитать площади в квадратных миллиметрах, что не предусмотрено boost::units. На 52 строке организовал костыль, позволяющий обходиться без новых типов данных,
с 6 по 22 пытался создать новый тип данных, масштабирующий базовые единицы измерения до необходимых, безуспешно
на 66 строке не удается вычесть triangleSquare из sectorSquare из-за несоответствия типов данных. Пробовал задать типы данных через auto - безуспешно

**Comment by Ted-Denisenko** [comment]
@dr-silence, есть какие-нибудь мысли/идеи, что можно попробовать сделать?

**Comment by dr-silence** [comment]
Нужны текст ошибки и скриншот ошибки

**Comment by Ted-Denisenko** [comment]
> Нужны текст ошибки и скриншот ошибки

 - Error	C2440	'initializing': cannot convert from 'boost::units::quantity<boost::units::unit<boost::units::area_dimension,boost::units::si::system,void>,double>' to 'boost::units::quantity<squared_millimeters,double>'
 - Error	C2676	binary '-': 'boost::units::quantity<boost::units::unit<boost::units::area_dimension,boost::units::si::system,void>,double>' does not define this operator or a conversion to a type acceptable to the predefined operator
![image](https://user-images.githubusercontent.com/91020107/183560766-cfb16957-ee8e-41b1-80cd-323751bca10f.png)

**Comment by dr-silence** [comment]
Представляется, что единицы измерения левой части не соответствуют единицам измерения правой части.

**Comment by Ted-Denisenko** [comment]
> единицы измерения левой части не соответствуют единицам измерения правой части.
 Да, я тоже пришел к такому выводу. По шаблону [отсюда](https://stackoverflow.com/questions/14724063/millimeters-in-boostunits) создал пользовательскую масштабированную единицу измерения, но теперь столкнулся с другой ошибкой - не высчитывается площадь
![image](https://user-images.githubusercontent.com/91020107/183568522-1079660f-0d33-4d9d-8a5e-07d95d0b3523.png)

**Comment by Ted-Denisenko** [comment]
Понял, что неправильно использовал scaled_base_unit, отчего было так много ошибок, сейчас пытаюсь адаптировать под мои цели make_scaled_unit, но пока что осталась одна ошибка, с которой еще не могу разобраться
![image](https://user-images.githubusercontent.com/91020107/183862081-295270b4-2c38-430e-af8e-b99fd397660b.png)

**Comment by Ted-Denisenko** [comment]
Можно было обойтись без определения нового типа данных. Прификсы работают и с обычными единицами измерения (напр., ед. измерения площади * на 'milli'(10^-3))
