### ISSUE TITLE
Реализовать расчёты с использованием ООП

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#44]
В соответствие с [вариантом №4](https://docs.google.com/document/d/1mgUwp20D0uvH53vgxJbwfOQ8Tq3IU0_MuJ8oBSSNYOI/edit?usp=drivesdk) расчеты объёмов реализовать с использованием подходов ООП:
- описать классы C++, представляющие соответствующие классы объектов, рассматриваемых в задаче;
- обязательно реализоваться иерархию классов C++, отражающую реальную иерархию понятий задачи;
- расчёт объёмов резервуаров различных видов реализовать с использованием полиморфизма;
- обеспечить сокрытие данных (инкапсуляцию).

**Comment by dr-silence** [comment]
Для реализации этой задачи необходимо оформить отдельные задачи, соответствующие отдельным этапам реализации, указанным а описании.

**Comment by dr-silence** [comment]
Необходимо постепенно фиксировать в репозитории решения отдельных задач, не пытаться одним коммитом решить все задачи. Реализовал требуемые классы C++ - зафиксируйт решение в репозитории, при этом сошлись на соответствующую дополнительную задачу.

**Comment by Ted-Denisenko** [comment]
Реализовано в [этом коммите](https://github.com/Ted-Denisenko/Storage_tank/commit/4eafa0bd4d2ec268bc61e8730bc08e671b80efee)
