### ISSUE TITLE
Избавить StorageTank от взаимодействия с пользователем

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#61]
Реализация взаимодействия с пользователем (вывод сообщений) в класса StorageTank нарушает [принцип единственной ответственности класса](https://en.wikipedia.org/wiki/Single-responsibility_principle): вместо того, чтобы заниматься лишь расчетами, класс StorageTank должен ещё и заботиться о взаимодействии с пользователем.

Необходимо избавить класс StorageTank от реализации взаимодействия с пользователем.

**Comment by Ted-Denisenko** [comment]
> Необходимо избавить класс StorageTank от реализации взаимодействия с пользователем.
@dr-silence , т.е. классы VerticalStorageTank и HorizontalStorageTank должны взаимодействовать с пользователем?

**Comment by dr-silence** [comment]
Подумай

**Comment by Ted-Denisenko** [comment]
> Подумай

Пока что вижу два варианта решения задачи:
 - сделать методы взаимодействия с пользователем виртуальными и описать их для каждого дочернего класса(функционал одинаковый, противоречит [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself))
  - убрать из родительского класса методы взаимодействия с пользователем и перенести их в дочерние классы(противоречит [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), двукратно увеличивает исходный код без изменения функционала)
  
  Мне нужно использовать один из вариантов выше, или есть лучшие способы решения задачи?

**Comment by dr-silence** [comment]
> Реализация взаимодействия с пользователем (вывод сообщений) в класса StorageTank нарушает [принцип единственной ответственности класса](https://en.wikipedia.org/wiki/Single-responsibility_principle): вместо того, чтобы заниматься лишь расчетами, класс StorageTank должен ещё и заботиться о взаимодействии с пользователем.
> 
> Необходимо избавить класс StorageTank от реализации взаимодействия с пользователем.

Как предложенные варианты соотносятся с данными указаниями?

**Comment by Ted-Denisenko** [comment]
> Как предложенные варианты соотносятся с данными указаниями?
> > Реализация взаимодействия с пользователем (вывод сообщений) в класса StorageTank нарушает [принцип единственной ответственности класса](https://en.wikipedia.org/wiki/Single-responsibility_principle)

Как я понимаю задачу, класс StorageTank не должен взаимодействовать с пользователем, но при этом необходимо сохранить возможность вывода результатов вычислений объема и массы содержимого. Так можно сделать, только добавив соотвествующий функционал классам-наследникам StorageTank
Если такой ффункционал не нужен впринципе, методы можно убрать из всех классов, оставив только вычисление данных

**Comment by dr-silence** [comment]
> Так можно сделать, только добавив соотвествующий функционал классам-наследникам StorageTank 

Верно ли я понял твоё утверждение: избавить класс StorageTank от взаимодействия с пользователем можно, лишь перенеся это взаимодействие в классы-потомки StorageTank?

**Comment by Ted-Denisenko** [comment]
> избавить класс StorageTank от взаимодействия с пользователем можно, лишь перенеся это взаимодействие в классы-потомки StorageTank?

Еще можно использовать дружеские функции, но больше мне вариантов на ум не приходит

**Comment by dr-silence** [comment]
На данный момент задача не решена. Не только StorageTank содержит код взаимодействия с пользователем, но и производные классы содержат код взаимодействия с пользователем.
