### ISSUE TITLE
Реализовать изменение уровня содержимого резервуара

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#66]
Уровень содержимого и производные величины - масса, объём, не являются постоянными характеристиками. Ибо очевидно, что уровень содержимого реального резервуара изменяется с течением времени.

Необходимо реализовать возможность изменять уровень содержимого резервуара.

**Comment by Ted-Denisenko** [comment]
> Необходимо реализовать возможность изменять уровень содержимого резервуара.

Не понимаю задачи. Перед каждым запуском программы указывается уровень наполнения резервуара, т.е. "возможность изменять уровень содержимого резервуара" уже есть. Нужно дать возможность менять уровень в процессе работы программы?

**Comment by Ted-Denisenko** [comment]
В коммите выше реализовал возможность изменять уровень содержимого с помощью сеттера в классе StorageTank

**Comment by dr-silence** [comment]
**Один и тот же экземпляр** резервуара должен позволять вычислять массу/объём для любого уровня.

**Comment by dr-silence** [comment]
> **Один и тот же экземпляр** резервуара должен позволять вычислять массу/объём для любого уровня.

Действительно, это было реализовано в коммите cd365e2f4bddd0ed9dd81e1626cb9df7723593ec.
