### ISSUE TITLE
Уровень содержимого представлять целым числом

### ISSUE THREAD

**Issue by dr-silence** [Ted-Denisenko/Storage_tank#68]
Уровень содержимого задаётся целым, не дробным, количеством миллиметров. Поэтому необходимо и в программе уровень представлять целым, а не вещественным числом.

**Comment by Ted-Denisenko** [comment]
Реализовано в [этом коммите](https://github.com/Ted-Denisenko/Storage_tank/commit/c52ba4f3021e526adeabb9e55d8c9f2a82549833)
